FROM alpine:latest

RUN wget https://github.com/aws/amazon-ec2-metadata-mock/releases/download/v1.11.2/ec2-metadata-mock-linux-amd64 -O /usr/local/bin/ec2-metadata-mock \
    && chmod 755 /usr/local/bin/ec2-metadata-mock

ENTRYPOINT ["/usr/local/bin/ec2-metadata-mock"]
CMD ["-p", "80"]
